# Generated by Django 2.2.4 on 2021-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_game',
            name='release_date',
            field=models.DateField(),
        ),
    ]
